export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  qboClientId: process.env.QBO_CLIENT_ID ?? "",
  qboClientSecret: process.env.QBO_CLIENT_SECRET ?? "",
  qboEnvironment: process.env.QBO_ENVIRONMENT ?? "sandbox",
  sevenShiftsAccessToken: process.env.SEVEN_SHIFTS_ACCESS_TOKEN ?? "",
  koomiAdminEmail: process.env.KOOMI_ADMIN_EMAIL ?? "",
  koomiAdminPassword: process.env.KOOMI_ADMIN_PASSWORD ?? "",
  azureClientId: process.env.AZURE_CLIENT_ID ?? "",
  azureTenantId: process.env.AZURE_TENANT_ID ?? "",
  azureClientSecret: process.env.AZURE_CLIENT_SECRET ?? "",
};
